# Generated by Django 5.2.9 on 2025-12-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoDeEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Formato de Emisión')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Anime')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('generos', models.CharField(max_length=100, verbose_name='Géneros')),
                ('numEpisodios', models.CharField(max_length=10, verbose_name='Número de Episodios')),
                ('formatoDeEmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.formatodeemision', verbose_name='Formato de Emisión')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.CharField(max_length=10, verbose_name='ID Usuario')),
                ('puntuacion', models.FloatField(verbose_name='Puntuación')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
        ),
    ]
